### ISSUE TITLE
p11keygen ignores some of unknown argument

### ISSUE THREAD

**Issue by wiwiwa** [Mastercard/pkcs11-tools#35]
**Describe the bug**
p11keygen simply ignores unknown argument if argument starts with unicode characters

**To Reproduce**
1. run `p11keygen -i test_key -k rsa WRAP £UNWRAP`, success to generate key
2. run `p11ls prvk/test_key` outputs `prvk/test_key tok,prv,r/w,loc,sen,ase,nxt,rsa(2048)`. No`unw` attribute found

**Expected behavior**
run `p11keygen -i test_key -k rsa WRAP £UNWRAP` should fail with error message

**Operating System (please complete the following information):**
 - OS: Oracle Linux 7
 - Kernel Version: 3.10.0 x86_64

**Comment by keldonin** [comment]
Thanks @wiwiwa , The issue is indeed confirmed. 

It seems that all subsequent arguments following `£` character are ignored.

I suspect the issue to be caused by the character itelf: `£` is not ASCII. Its Unicode representation is `0x00 0xa3`; it is likely that the parser stops string interpretation when the first `0x00` is encountered.

**Comment by keldonin** [comment]
The issue is happening at the parser & lexer level. Unless there is an imperative reason to fix it, I'll leave this one as is.
