### ISSUE TITLE
OpenSSL 1.1.1, Cryptoki 2.40, possibly Cryptoki v3 EdDSA features?

### ISSUE THREAD

**Issue by nickray** [Mastercard/pkcs11-tools#5]
Hi Eric,
great project! I see in https://github.com/Mastercard/pkcs11-tools/projects/1 that you're planning to support OpenSSL 1.1 and update to Cryptoki 2.40, is this actively being worked on, in the sense having an idea when it will land?

Additionally, it would be great to already have support for EdDSA: it should be included in PKCS#11 version 3, there is a [draft that looks close to final](https://www.oasis-open.org/committees/document.php?document_id=62198&wg_abbrev=pkcs11), and SoftHSMv2 [added support in 2.5](https://github.com/opendnssec/SoftHSMv2/pull/362).

**Comment by nickray** [comment]
Thanks for the quick response! Yes indeed openssl 1.1 is a bit disruptive isn't it; on the (non-enterprisey) distributions I use openssl 1.0 isn't even easily available anymore though.

Regards to 25519, from what I can tell it's "just" three new constants plus implementation to cherry-pick this back into 2.40; I'm working on a patch for [python-pkcs11](https://github.com/nickray/python-pkcs11/commit/72c7e28e40958016447265df7c27d98df072d5d1). As linked above, SoftHSMv2 added support in their version 2.5, so I assume it there aren't any compatibility issues - it's new functionality.

**Comment by keldonin** [comment]
Just constants? Do you know which mechanisms this will affect? key pair generation/signature/verification, presumably? I can imagine, also, that another OID must be picked as signature algorithm, ( i.e. EdDSA instead of ECDSA).

python-pkcs11 is another project I have been contributing recently. I'm on the watchers list, I'll check your patch once you have published your PR, to gather the information.

Adding EdDSA as a distinct feature to develop, in my project plan.


Stay tuned.

**Comment by keldonin** [comment]
Support for PKCS#2.40 fixed in v1.1.0 (commit 2ab2172)

**Comment by keldonin** [comment]
- Support for OpenSSL 1.1+ moved to issue #10 
- Support for EdDSA curves moved to issue #11

**Comment by keldonin** [comment]
Hi @nickray,

PKCS#11 3.0, OpenSSL 1.1.1 and Edwards curve is  supported as of release v2.1.0.

Regards,
